name: AUT - trigger SEA

on:
  schedule:
    - cron: "30 1 * * 4"   # 08:30 GMT+7 thứ 5
  workflow_dispatch:

jobs:
  trigger:
    runs-on: ubuntu-latest
    steps:
      - name: Wake SEA repo
        env:
          PAT: ${{ secrets.AUT_PAT }}
        run: |
          curl -s -o /dev/null -w "%{http_code}\n" \
            -X POST \
            -H "Authorization: Bearer ${PAT}" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/phuckaka1991-svg/blackvn-sea-notice/actions/workflows/sea.yml/dispatches \
            -d '{"ref":"main"}'
