name: AUT - trigger GLOBAL LAB

on:
  schedule:
    - cron: "30 8 * * 5"   # 15:30 GMT+7 thứ 6
  workflow_dispatch:

jobs:
  trigger:
    runs-on: ubuntu-latest
    env:
      OWNER: phuckaka1991-svg
      REPO:  blackvn-global-lab
      WORKFLOW_FILE: global-lab.yml   # PHẢI ĐÚNG tên file trong .github/workflows/ của repo con
      REF:   main                 # Nhánh tồn tại ở repo con
    steps:
      - name: Check AUT_PAT present
        run: |
          test -n "${{ secrets.AUT_PAT }}" || { echo "❌ Missing AUT_PAT secret"; exit 1; }

      - name: Resolve workflow ID from file name
        run: |
          curl -sS -H "Authorization: Bearer ${{ secrets.AUT_PAT }}" \
               -H "Accept: application/vnd.github+json" \
               "https://api.github.com/repos/$OWNER/$REPO/actions/workflows/$WORKFLOW_FILE" \
               | tee resp.json
          id=$(grep -o '"id":[ ]*[0-9]\+' resp.json | head -n1 | sed 's/[^0-9]//g')
          if [ -z "$id" ]; then
            echo "❌ Không tìm thấy workflow ($WORKFLOW_FILE) – sai tên file hoặc PAT thiếu quyền."
            cat resp.json
            exit 1
          fi
          echo "WORKFLOW_ID=$id" >> $GITHUB_ENV
          echo "✅ Workflow ID: $id"

      - name: Dispatch workflow by ID
        run: |
          echo "Dispatch to $OWNER/$REPO ref=$REF id=$WORKFLOW_ID"
          code=$(curl -sS -o /tmp/resp.txt -w "%{http_code}" -X POST \
            -H "Authorization: Bearer ${{ secrets.AUT_PAT }}" \
            -H "Accept: application/vnd.github+json" \
            "https://api.github.com/repos/$OWNER/$REPO/actions/workflows/$WORKFLOW_ID/dispatches" \
            -d "{\"ref\":\"$REF\"}")
          echo "HTTP $code"
          cat /tmp/resp.txt || true
          # Thành công phải là 204 No Content
          test "$code" = "204"
